# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Get merged pull requests
        uses: VanOns/get-merged-pull-requests-action@v1
        id: pull_requests
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print merged pull requests
        env:
          PULL_REQUESTS_FILE: ${{ steps.pull_requests.outputs.pull_requests_file }}
          CURRENT_VERSION: ${{ github.ref_name }}
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
          git tag
          git describe
          echo $PWD
          if [ ! -d ".git" ]; then
            echo "Not in  a git folder"
          fi
          echo "tags : $(git tag --sort=-creatordate)"
          LAST_VERSION=$(git tag --sort=-creatordate | sed -n '2p')
          FOLDER="dist"
          if [ ! -d "$FOLDER" ]; then
            mkdir "$FOLDER"
          fi
          INFO_FILE="${FOLDER}/release.md"
          echo "## What's Changed" > $INFO_FILE
          if [ -z "$PULL_REQUESTS_FILE" ] || [ ! -f "$PULL_REQUESTS_FILE" ]; then
            echo "No change via Pull Request. Change log should be done manually." >> $INFO_FILE
            exit 0
          fi
          
          titles=$(jq -r '.[] | "- " + .title + " (Pr: #" + (.number | tostring) + " by @" + .user.login + ")"' "$PULL_REQUESTS_FILE"| sort | uniq)
          
          if [ -z "$titles" ]; then
            echo "No change via Pull Request. Change log should be done manually." >> $INFO_FILE
          else
            
            echo "$titles" | while read -r title; do
              echo "$title" >> $INFO_FILE
            done
          fi
          echo -e "\n**Full Changelog**: https://github.com/Houssame-EA/IsotopeTrack/compare/${LAST_VERSION}...${CURRENT_VERSION}" >> $INFO_FILE

          cat $INFO_FILE
