on:
  release:
    types: [published]

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v6
        with:
          latest-version: ${{ github.event.release.tag_name }}
          release-notes: ${{ github.event.release.body }}

      - name: Commit CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update CHANGELOG
          changelog-body: docs/changelog.md
